Repository neutrinojs/neutrino, pull requests merged in 2018-07, with the labels that each got.

#975 Fix Neutrino usage of yargs
  packages/neutrino/bin/neutrino.js
  packages/neutrino/index.js
Labels: bug

#977 library: Correct inverted conditional for node polyfill config
  packages/library/index.js
Labels: bug

#983 Move @neutrinojs/env into the web preset & support default values
  docs/packages/env.md
  mkdocs.yml
  packages/env/.npmignore
  packages/env/README.md
  packages/env/index.js
  packages/env/package.json
  packages/env/test/middleware_test.js
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
  packages/web/test/web_test.js
Labels: breaking change, feature

#991 node: Target the version of Node.js used to run webpack
  packages/node/README.md
  packages/node/index.js
Labels: breaking change

#990 Ensure output override is a function
  packages/neutrino/index.js
  packages/neutrino/test/package_test.js
Labels: bug

#994 Target IE9 as the browser to support ES5 compilation
  packages/library/README.md
  packages/library/index.js
  packages/react-components/README.md
  packages/react-components/index.js
Labels: breaking change

#972 Improve mode/NODE_ENV defaults and interaction
  packages/create-project/commands/init/templates/jest/jest.config.js
  packages/create-project/commands/init/templates/karma/karma.conf.js
  packages/create-project/commands/init/templates/mocha/mocha.config.js
  packages/eslint/README.md
  packages/eslint/index.js
  packages/font-loader/README.md
  packages/font-loader/index.js
  packages/image-loader/README.md
  packages/image-loader/index.js
  packages/image-minify/index.js
  packages/image-minify/test/middleware_test.js
  packages/jest/test/jest_test.js
  packages/karma/test/karma_test.js
  packages/library/index.js
  packages/library/test/library_test.js
  packages/mocha/test/mocha_test.js
  packages/neutrino/index.js
  packages/neutrino/test/package_test.js
  packages/node/index.js
  packages/node/test/node_test.js
  packages/preact/test/preact_test.js
  packages/react-components/index.js
  packages/react-components/test/components_test.js
  packages/react/index.js
  packages/react/test/react_test.js
  packages/style-loader/README.md
  packages/style-loader/index.js
  packages/stylelint/README.md
  packages/stylelint/index.js
  packages/vue/index.js
  packages/vue/test/vue_test.js
  packages/web/index.js
  packages/web/test/web_test.js
Labels: bug

#995 Simplify the output handler API
  packages/compile-loader/index.js
  packages/eslint/index.js
  packages/jest/src/index.js
  packages/karma/index.js
  packages/mocha/src/index.js
  packages/neutrino/index.js
  packages/neutrino/test/package_test.js
  packages/neutrino/webpack.js
  packages/stylelint/index.js
Labels: breaking change
