Repository neutrinojs/neutrino, pull requests merged in 2018-04, with the labels that each got.

#703 Update the suggested .eslintrc.js shim so it can find .neutrinorc.js from any location
  docs/api/README.md
  docs/migration-guide.md
  docs/packages/airbnb-base/README.md
  docs/packages/airbnb/README.md
  docs/packages/eslint/README.md
  docs/packages/standardjs/README.md
  docs/packages/stylelint/README.md
  packages/airbnb-base/README.md
  packages/airbnb/README.md
  packages/eslint/README.md
  packages/standardjs/README.md
  packages/stylelint/README.md
Labels: docs

#815 Split up the minify preset
  docs/SUMMARY.md
  docs/customization/README.md
  docs/middleware/README.md
  docs/packages/image-minify/README.md
  docs/packages/library/README.md
  docs/packages/minify/README.md
  docs/packages/web/README.md
  packages/image-minify/README.md
  packages/image-minify/index.js
  packages/image-minify/test/middleware_test.js
  packages/library/README.md
  packages/library/index.js
  packages/library/package.json
  packages/minify/.npmignore
  packages/minify/README.md
  packages/minify/index.js
  packages/minify/package.json
  packages/minify/test/middleware_test.js
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
  packages/web/test/web_test.js
Labels: breaking change

#817 Use package manager to trigger lint fix instead of neutrino bin on PATH
  packages/create-project/commands/init/index.js
Labels: bug

#826 compile-loader: Set 'babelrc' to false
  packages/compile-loader/index.js
Labels: breaking change

#829 Remove legacy gitbook functionality
  .gitbook.yaml
  .gitignore
  book.json
  docs/SUMMARY.md
  docs/contributing/development.md
  docs/middleware/community-middleware.md
  docs/presets/community-presets.md
  package.json
  renovate.json
  yarn.lock
Labels: docs
