Repository neutrinojs/neutrino, pull requests merged in 2018-12, with the labels that each got.

#1240 Doc typo in style-loader
  packages/style-loader/README.md
Labels: docs

#1242 Vue/Style: Use passed style.test option as default instead of forcing css
  packages/vue/index.js
Labels: bug

#1265 create-project: Display lint command output when using --debug
  packages/create-project/bin/create-project.js
  packages/create-project/commands/init/index.js
Labels: bug

#1266 create-project: Run correct command for initial lint when using npm
  docs/usage.md
  packages/create-project/commands/init/index.js
Labels: bug

#1254 Remove manifest plugin
  docs/migration-guide.md
  packages/react-components/index.js
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
  packages/web/test/web_test.js
  yarn.lock
Labels: breaking change

#1267 create-project: Skip directory cleanup on errors when using debug
  packages/create-project/commands/init/index.js
Labels: feature
