Repository neutrinojs/neutrino, pull requests merged in 2018-09, with the labels that each got.

#1072 Reduce verbosity of webpack compile output
  packages/dev-server/index.js
  packages/karma/index.js
  packages/library/index.js
  packages/library/test/library_test.js
  packages/node/index.js
  packages/node/test/node_test.js
  packages/web/index.js
  packages/web/test/web_test.js
Labels: breaking change

#1076 Docs: Correct the order of loaders in postcss-loader example
  packages/style-loader/README.md
Labels: docs

#1069 web/library: Remove worker-loader
  packages/library/README.md
  packages/library/index.js
  packages/library/package.json
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
Labels: breaking change

#1064 Added .web.js{x} resolve extensions to webpack for better react-native-web support
  packages/react/index.js
  packages/react/test/react_test.js
Labels: feature

#1082 Test create-project buildable in development mode
  packages/create-project/test/cli_test.js
Labels: development

#1081 Support options for jest and karma presets in v9
  packages/jest/package.json
  packages/jest/src/index.js
  packages/jest/test/jest_test.js
  packages/karma/index.js
  packages/karma/test/karma_test.js
Labels: bug

#1083 Stop removing webpack plugins from webpack-karma
  packages/karma/index.js
Labels: bug

#1062 Add devtool option to web preset
  packages/web/index.js
  packages/web/test/web_test.js
Labels: feature

#1080 Converge extension priority parity with that of webpack
  packages/create-project/commands/init/index.js
  packages/library/test/library_test.js
  packages/neutrino/extensions.js
  packages/node/test/node_test.js
  packages/react/index.js
  packages/web/test/web_test.js
Labels: breaking change

#1079 Throw errors that arise from spawning processes in create-project
  packages/create-project/commands/init/index.js
  packages/create-project/test/cli_test.js
Labels: bug

#1088 Add webpack-cli to peerDependencies
  packages/library/package.json
  packages/node/package.json
  packages/preact/package.json
  packages/react-components/package.json
  packages/react/package.json
  packages/vue/package.json
  packages/web/package.json
Labels: breaking change

#1087 Update to html-webpack-plugin 4.0.0-alpha.2
  packages/html-template/package.json
  packages/react-components/index.js
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
  yarn.lock
Labels: breaking change, performance

#1099 Make removal of the 'polyfills' option more obvious
  packages/library/index.js
  packages/library/test/library_test.js
  packages/node/index.js
  packages/node/test/node_test.js
  packages/web/index.js
  packages/web/test/web_test.js
Labels: breaking change

#1101 Lazily require() webpack plugins to improve performance
  docs/webpack-chain.md
  packages/banner/index.js
  packages/clean/index.js
  packages/copy/index.js
  packages/html-template/index.js
  packages/image-minify/index.js
  packages/neutrino/package.json
  packages/node/index.js
  packages/pwa/index.js
  packages/start-server/index.js
  packages/style-loader/index.js
  packages/style-minify/index.js
  packages/stylelint/index.js
  packages/vue/index.js
  packages/web/index.js
  yarn.lock
Labels: performance

#1098 Migration guide for v8 to v9
  docs/migration-guide.md
Labels: docs

#1105 Remove image-minify middleware
  docs/migration-guide.md
  docs/packages/image-minify.md
  mkdocs.yml
  packages/image-minify/.npmignore
  packages/image-minify/README.md
  packages/image-minify/index.js
  packages/image-minify/package.json
  packages/image-minify/test/middleware_test.js
  yarn.lock
Labels: breaking change

#1107 Respect passing false to style-loader modules
  packages/style-loader/index.js
  packages/style-loader/test/middleware_test.js
Labels: bug

#1011 [v8.x] Fix Babel minification documentation
  docs/packages/web/README.md
  packages/web/README.md
Labels: docs

#1115 Reorganize and nest docs navigation for readability
  mkdocs.yml
Labels: docs

#1110 Remove stylelint middleware
  docs/migration-guide.md
  docs/packages/stylelint.md
  mkdocs.yml
  package.json
  packages/stylelint/.npmignore
  packages/stylelint/README.md
  packages/stylelint/index.js
  packages/stylelint/package.json
  packages/stylelint/test/middleware_test.js
  packages/vue/index.js
  packages/vue/package.json
  yarn.lock
Labels: breaking change

#1114 Usage docs: linting with ESLint CLI
  docs/usage.md
Labels: docs

#1113 Remove TypeScript extensions, make vue preset control its extension
  docs/migration-guide.md
  packages/airbnb-base/README.md
  packages/airbnb/README.md
  packages/create-project/commands/init/index.js
  packages/eslint/README.md
  packages/library/test/library_test.js
  packages/neutrino/extensions.js
  packages/node/test/node_test.js
  packages/standardjs/README.md
  packages/vue/index.js
  packages/vue/test/vue_test.js
  packages/web/test/web_test.js
Labels: breaking change

#1116 Docs: Remove leftover references to 'neutrino build'
  packages/airbnb-base/README.md
  packages/airbnb/README.md
  packages/library/README.md
  packages/node/README.md
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/standardjs/README.md
  packages/vue/README.md
  packages/web/README.md
Labels: docs

#1117 Remove old docs snippets that reference webpack 3 build output
  packages/library/README.md
  packages/node/README.md
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
Labels: docs

#1118 Add webpack-dev-server to react-components' dependencies to make it startable, make note in react-components README about conflict with eslint-plugin-import
  packages/create-project/commands/init/matrix.js
  packages/react-components/README.md
Labels: bug, docs

#1120 Move inspect to its own handler
  packages/neutrino/bin/neutrino.js
  packages/neutrino/handlers.js
  packages/neutrino/index.js
  packages/neutrino/test/package_test.js
  packages/neutrino/webpack.js
Labels: breaking change

#1121 html-template: Adjust minification settings to match upstream
  packages/html-template/README.md
  packages/html-template/index.js
  packages/html-template/package.json
  packages/html-template/test/middleware_test.js
Labels: breaking change

#1122 Add webpack-dev-server to web-relevant presets' peerDependencies
  packages/create-project/commands/init/matrix.js
  packages/preact/package.json
  packages/react-components/package.json
  packages/react/package.json
  packages/vue/package.json
  packages/web/package.json
Labels: bug

#1123 Update READMEs and snippet outputs for v9
  packages/airbnb-base/README.md
  packages/airbnb/README.md
  packages/jest/README.md
  packages/karma/README.md
  packages/mocha/README.md
  packages/neutrino/README.md
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/standardjs/README.md
  packages/vue/README.md
  packages/web/README.md
Labels: docs

#1124 Add documentation notes about compiling node_modules
  packages/compile-loader/README.md
  packages/library/README.md
  packages/node/README.md
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
Labels: docs

#1127 Remove reference to fork middleware in library preset by prompoting multiple webpack outputs
  docs/usage.md
  packages/library/README.md
Labels: docs

#1128 Docs: Clean up some links that were redirecting
  README.md
  docs/index.md
  packages/compile-loader/README.md
  packages/react/README.md
Labels: docs

#1136 Set ESLint CLI --format to 'codeframe'
  docs/migration-guide.md
  docs/usage.md
  package.json
  packages/airbnb-base/README.md
  packages/airbnb/README.md
  packages/create-project/commands/init/index.js
  packages/eslint/README.md
  packages/standardjs/README.md
Labels: bug

#1135 Use 'webpack-dev-server --open' for new projects
  docs/migration-guide.md
  docs/usage.md
  packages/create-project/commands/init/index.js
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
Labels: feature

#1138 Refresh lockfile & bump in-range dependency versions
  package.json
  packages/compile-loader/package.json
  packages/copy/package.json
  packages/create-project/package.json
  packages/eslint/package.json
  packages/image-loader/package.json
  packages/jest/package.json
  packages/karma/package.json
  packages/library/package.json
  packages/mocha/package.json
  packages/node/package.json
  packages/preact/package.json
  packages/pwa/package.json
  packages/react/package.json
  packages/standardjs/package.json
  packages/style-loader/package.json
  packages/style-minify/package.json
  packages/vue/package.json
  packages/web/package.json
  yarn.lock
Labels: breaking change

#1139 Add RFC forwarded header as hint to backend server
  packages/web/index.js
Labels: breaking change

#1148 eslint: Pass formatter to eslint-loader as a string
  packages/eslint/README.md
  packages/eslint/index.js
  packages/eslint/test/middleware_test.js
Labels: bug
