Repository neutrinojs/neutrino, pull requests merged in 2018-08, with the labels that each got.

#1010 Docs: Sync webpack-chain page with upstream README
  docs/webpack-chain.md
Labels: docs

#1021 Docs: Update to mkdocs v1 and mkdocs-material v3
  docs/requirements.txt
  docs/runtime.txt
  docs/v4.md
  docs/v5.md
  docs/v6.md
  docs/v7.md
  docs/v8.md
  mkdocs.yml
  netlify.toml
  scripts/build-docs.sh
Labels: docs

#1025 Update to ESLint 5
  package.json
  packages/airbnb-base/package.json
  packages/airbnb/package.json
  packages/create-project/commands/init/matrix.js
  packages/eslint/README.md
  packages/eslint/index.js
  packages/eslint/package.json
  packages/jest/package.json
  packages/react/package.json
  packages/standardjs/package.json
  packages/vue/package.json
  yarn.lock
Labels: breaking change

#1029 Support per-page HTML template customisation via 'mains'
  docs/api.md
  docs/creating-presets.md
  docs/customization.md
  packages/library/index.js
  packages/neutrino/Neutrino.js
  packages/neutrino/test/api_test.js
  packages/node/index.js
  packages/react-components/index.js
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
  packages/web/index.js
  packages/web/test/web_test.js
Labels: breaking change, feature

#1030 Jest: Set testEnvironment to 'node' when targeting node
  packages/jest/src/index.js
Labels: breaking change, bug

#1040 Fix respecting externals options in library middleware
  packages/library/index.js
Labels: bug

#1052 Stop using eslint-plugin-babel's 'babel/quotes' rule
  packages/airbnb-base/index.js
  packages/airbnb/index.js
  packages/standardjs/index.js
Labels: breaking change

#1049 html-template: Replace html-webpack-template with our own template
  packages/html-template/README.md
  packages/html-template/index.js
  packages/html-template/package.json
  packages/html-template/template.ejs
  packages/web/test/web_test.js
  yarn.lock
Labels: breaking change

#1041 Specify root option for monorepo scripts and project creation
  .eslintignore
  .eslintrc.js
  .neutrinorc.js
  package.json
  packages/airbnb-base/eslintrc.js
  packages/airbnb/eslintrc.js
  packages/create-project/commands/init/index.js
  packages/create-project/commands/init/templates/mocha/mocha.config.js
  packages/eslint/eslintrc.js
  packages/neutrino/index.js
  packages/standardjs/eslintrc.js
Labels: bug, development

#1061 create-project: Update webpack-cli from v2 to v3
  package.json
  packages/create-project/commands/init/matrix.js
  yarn.lock
Labels: feature
