Repository neutrinojs/neutrino, pull requests merged in 2018-10, with the labels that each got.

#1149 Allow using browserlistsrc for targets
  packages/web/README.md
  packages/web/index.js
  packages/web/test/web_test.js
Labels: feature

#1157 Lock file maintenance
  yarn.lock
Labels: development

#1159 tests: Clean up t.throws() and async usage
  packages/eslint/test/middleware_test.js
  packages/library/test/library_test.js
  packages/neutrino/test/package_test.js
  packages/neutrino/test/require_test.js
  packages/node/test/node_test.js
  packages/web/test/web_test.js
Labels: development

#1154 compile-loader: Set 'configFile' to false by default
  packages/compile-loader/index.js
Labels: breaking change

#1160 Improvements to the Neutrino 9 migration UX
  docs/migration-guide.md
  packages/html-template/index.js
  packages/html-template/test/middleware_test.js
  packages/neutrino/bin/neutrino.js
  packages/node/test/node_test.js
  packages/web/index.js
  packages/web/test/web_test.js
Labels: bug, docs

#1158 Switch to terser-webpack-plugin
  docs/migration-guide.md
  packages/library/README.md
  packages/library/index.js
  packages/library/package.json
  packages/library/test/library_test.js
  packages/neutrino/handlers.js
  packages/neutrino/test/package_test.js
  packages/node/README.md
  packages/node/index.js
  packages/node/package.json
  packages/node/test/node_test.js
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
  packages/web/test/web_test.js
  yarn.lock
Labels: breaking change, bug, performance

#1168 dev-server: Remove redundant 'open' option
  packages/dev-server/README.md
  packages/dev-server/index.js
Labels: cleanup

#1165 dev-server: Stop setting contentBase
  docs/migration-guide.md
  packages/dev-server/README.md
  packages/dev-server/index.js
Labels: breaking change

#1163 Clean up the display of errors during middleware instantiation
  packages/neutrino/index.js
Labels: bug

#1162 Add checks for middleware being used twice unintentionally
  docs/migration-guide.md
  packages/compile-loader/index.js
  packages/compile-loader/test/middleware_test.js
  packages/eslint/index.js
  packages/eslint/test/middleware_test.js
  packages/font-loader/index.js
  packages/font-loader/test/middleware_test.js
  packages/html-template/index.js
  packages/image-loader/index.js
  packages/image-loader/test/middleware_test.js
  packages/library/index.js
  packages/neutrino/Neutrino.js
  packages/neutrino/errors.js
  packages/neutrino/handlers.js
  packages/node/index.js
  packages/style-loader/index.js
  packages/style-loader/test/middleware_test.js
  packages/web/index.js
  packages/web/test/web_test.js
Labels: breaking change

#1173 docs: Correct PR # for contentBase change
  docs/migration-guide.md
Labels: docs

#1174 Output generated files under an assets/ subdirectory
  docs/migration-guide.md
  packages/font-loader/README.md
  packages/font-loader/index.js
  packages/image-loader/README.md
  packages/image-loader/index.js
  packages/library/index.js
  packages/node/index.js
  packages/react-components/index.js
  packages/style-loader/README.md
  packages/style-loader/index.js
  packages/web/index.js
Labels: breaking change, feature

#1175 Clean up dev-server options
  docs/migration-guide.md
  packages/dev-server/README.md
  packages/dev-server/index.js
  packages/dev-server/package.json
  packages/preact/README.md
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
  packages/web/index.js
  packages/web/test/web_test.js
Labels: breaking change, bug, cleanup

#1183 jest: Use babel-jest instead of a custom implementation
  packages/jest/package.json
  packages/jest/src/index.js
  packages/jest/src/transformer.js
  yarn.lock
Labels: breaking change, cleanup

#1184 eslint: Set the eslint-plugin-react react version to latest
  packages/airbnb/README.md
  packages/airbnb/index.js
  packages/airbnb/test/airbnb_test.js
  packages/react/index.js
  packages/react/test/react_test.js
  packages/standardjs/README.md
  packages/standardjs/index.js
  packages/standardjs/test/standardjs_test.js
Labels: breaking change

#1185 web: Default output.publicPath to '/'
  docs/migration-guide.md
  packages/preact/README.md
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
  packages/web/index.js
  packages/web/test/web_test.js
Labels: breaking change

#1190 Travis: Test against Node 11
  .travis.yml
Labels: development
