Repository neutrinojs/neutrino, pull requests merged in 2018-11, with the labels that each got.

#1214 react: Remove propTypes in production
  packages/react/index.js
  packages/react/package.json
  yarn.lock
Labels: breaking change

#1216 eslint: Downgrade linter errors to warnings in development
  packages/airbnb-base/test/airbnb_test.js
  packages/airbnb/test/airbnb_test.js
  packages/eslint/README.md
  packages/eslint/index.js
  packages/eslint/test/middleware_test.js
  packages/standardjs/test/standardjs_test.js
Labels: bug

#1217 dev-server: Enable in-page overlay for display of errors
  packages/dev-server/index.js
  packages/web/test/web_test.js
Labels: breaking change, feature

#1215 Use webpack's default value for `minimizer`
  docs/migration-guide.md
  package.json
  packages/library/README.md
  packages/library/index.js
  packages/library/package.json
  packages/library/test/library_test.js
  packages/neutrino/handlers.js
  packages/neutrino/test/package_test.js
  packages/node/README.md
  packages/node/index.js
  packages/node/package.json
  packages/node/test/node_test.js
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
  packages/web/test/web_test.js
  yarn.lock
Labels: breaking change, cleanup

#1208 added webstorm mocha runner documentation
  packages/mocha/README.md
Labels: docs

#1219 mocha: Use correct function for merging lint configuration
  packages/mocha/package.json
  packages/mocha/src/index.js
Labels: bug

#1222 jest: Add missing peer dependency
  packages/jest/package.json
  yarn.lock
Labels: bug

#1223 Stop adding .wasm to the compile/linting rules
  docs/api.md
  docs/creating-presets.md
  packages/airbnb-base/test/airbnb_test.js
  packages/airbnb/test/airbnb_test.js
  packages/eslint/test/middleware_test.js
  packages/library/index.js
  packages/neutrino/extensions.js
  packages/neutrino/test/api_test.js
  packages/node/index.js
  packages/standardjs/test/standardjs_test.js
  packages/vue/test/vue_test.js
  packages/web/index.js
Labels: bug

#1221 Move style extraction conditionals from web into style-loader
  docs/migration-guide.md
  packages/style-loader/README.md
  packages/style-loader/index.js
  packages/style-loader/test/middleware_test.js
  packages/vue/index.js
  packages/web/README.md
  packages/web/index.js
  packages/web/test/web_test.js
Labels: breaking change, bug

#1220 compile-loader: Remove babel-merge export
  docs/migration-guide.md
  packages/compile-loader/README.md
  packages/compile-loader/index.js
  packages/compile-loader/package.json
  packages/karma/index.js
  packages/karma/package.json
  packages/library/index.js
  packages/library/package.json
  packages/node/index.js
  packages/node/package.json
  packages/preact/index.js
  packages/preact/package.json
  packages/react/index.js
  packages/react/package.json
  packages/web/index.js
  packages/web/package.json
Labels: breaking change, cleanup

#1228 Default main entries to be the key name if not specified
  packages/neutrino/Neutrino.js
  packages/neutrino/test/api_test.js
Labels: bug

#1229 Docs: Preparation for Neutrino 9 release
  docs/migration-guide.md
  mkdocs.yml
Labels: docs

#1230 Update auto-changelog configuration
  .auto-changelog
  CHANGELOG.md
  package.json
Labels: docs
