Repository neutrinojs/neutrino, pull requests merged in 2018-06, with the labels that each got.

#922 Only test against Node 9 on master
  .travis.yml
Labels: development

#902 Migrate react preset and create-project to properly use RHL v4
  packages/create-project/commands/init/matrix.js
  packages/create-project/commands/init/templates/react/src/App.jsx
  packages/create-project/commands/init/templates/react/src/index.jsx
  packages/react/README.md
  packages/react/index.js
  packages/react/package.json
  packages/web/index.js
  yarn.lock
Labels: breaking change

#924 Remove nyc monorepo dependency
  package.json
  yarn.lock
Labels: development

#926 Use default webpack module resolution
  docs/api.md
  docs/creating-presets.md
  docs/customization.md
  packages/eslint/index.js
  packages/jest/src/index.js
  packages/library/index.js
  packages/neutrino/Neutrino.js
  packages/neutrino/test/api_test.js
  packages/node/index.js
  packages/preact/index.js
  packages/react-components/index.js
  packages/react/index.js
  packages/vue/index.js
  packages/web/index.js
Labels: breaking change

#930 Adjust hashes used in production asset filenames
  packages/font-loader/README.md
  packages/font-loader/index.js
  packages/image-loader/README.md
  packages/image-loader/index.js
  packages/node/index.js
  packages/style-loader/README.md
  packages/style-loader/index.js
  packages/web/index.js
Labels: breaking change

#934 Remove style minification from the web preset
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
  packages/web/test/web_test.js
Labels: breaking change

#935 [v8.x] Backport stringified config improvements as --inspect-new
  docs/api/README.md
  docs/cli/README.md
  packages/neutrino/bin/inspect.js
  packages/neutrino/bin/neutrino.js
  packages/neutrino/src/index.js
  packages/neutrino/src/inspect.js
Labels: feature

#941 [v8.x] loader-merge: Replace `object-rest-spread` example
  docs/migration-guide.md
  docs/packages/loader-merge/README.md
  packages/loader-merge/README.md
Labels: docs

#940 [v8.x] Add object rest spread support to web & library presets
  docs/packages/library/README.md
  docs/packages/preact/README.md
  docs/packages/react-components/README.md
  docs/packages/react/README.md
  docs/packages/vue/README.md
  docs/packages/web/README.md
  packages/library/README.md
  packages/library/index.js
  packages/library/package.json
  packages/preact/README.md
  packages/preact/index.js
  packages/preact/package.json
  packages/react-components/README.md
  packages/react/README.md
  packages/react/index.js
  packages/react/package.json
  packages/vue/README.md
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
Labels: feature

#936 dev-server: Suppress unhelpful stack trace for compile failures
  packages/dev-server/index.js
Labels: bug

#939 eslint: Throw if preset used after compile rule already defined
  packages/eslint/index.js
  packages/eslint/test/middleware_test.js
Labels: breaking change, bug

#937 karma: Correctly suppress webpack compile information
  packages/karma/index.js
Labels: breaking change

#942 [v8.x] dev-server: Suppress unhelpful stack trace for compile failures
  packages/dev-server/index.js
Labels: bug

#938 karma: Update karma-webpack to 4.0.0-beta.0
  packages/karma/package.json
  yarn.lock
Labels: breaking change

#943 html-loader: Add 'link:href' to attrs so favicons are parsed
  packages/html-loader/index.js
Labels: feature

#945 Correctly configure the eslint-plugin-babel replacement rules
  packages/airbnb-base/index.js
  packages/airbnb/index.js
  packages/airbnb/package.json
  packages/standardjs/index.js
Labels: breaking change, bug

#949 Monorepo linting improvements
  .eslintignore
  .neutrinorc.js
  package.json
  packages/create-project/commands/init/index.js
  packages/create-project/commands/init/templates/react-components/src/components/HelloWorld/index.jsx
  packages/create-project/commands/init/templates/react-components/src/index.jsx
  packages/create-project/commands/init/templates/vue/src/index.js
  packages/create-project/test/cli_test.js
  packages/eslint/index.js
  packages/eslint/test/middleware_test.js
  packages/image-minify/test/middleware_test.js
  packages/neutrino/Neutrino.js
  packages/neutrino/test/api_test.js
  packages/neutrino/test/fixtures/test-module/middleware.js
  packages/neutrino/test/package_test.js
  packages/neutrino/test/require_test.js
  packages/preact/package.json
  packages/react/package.json
  packages/vue/package.json
  yarn.lock
Labels: development

#951 eslint: Lint the tests directory by default too
  packages/eslint/README.md
  packages/eslint/index.js
Labels: breaking change

#957 create-project: Install a matching version of Neutrino packages
  packages/create-project/commands/init/index.js
  packages/create-project/commands/init/matrix.js
  packages/create-project/commands/init/questions.js
  packages/create-project/commands/init/utils.js
  scripts/test-create-project-ci.sh
Labels: bug

#966 create-project: Install a matching version of 'neutrino' too
  packages/create-project/commands/init/index.js
Labels: bug

#970 Update CHANGELOG on master for 8.3.0
  CHANGELOG.md
  package.json
Labels: docs
