Repository neutrinojs/neutrino, pull requests merged in 2019-05, with the labels that each got.

#1373 Release process revisions
  docs/contributing/development.md
Labels: development

#1372 Use native Node.js for pulling version
  package.json
Labels: development

#1379 Update dependencies and associated docs
  docs/webpack-chain.md
  packages/neutrino/package.json
  packages/standardjs/package.json
  yarn.lock
Labels: development, docs

#1383 Fix missing @babel/core peer dependency for karma preset
  packages/karma/package.json
Labels: bug

#1393 chore(readme): fix webpack-chain doc
  docs/webpack-chain.md
Labels: bug, docs

#1396 Detect yarn in create-project via environment
  packages/create-project/commands/init/utils.js
  packages/create-project/package.json
  yarn.lock
Labels: bug

#1397 Test create-project in CI with both npm and yarn
  .travis.yml
  packages/create-project/test/cli_test.js
  scripts/test-create-project-ci.sh
  verdaccio.npm.yml
  verdaccio.yarn.yml
Labels: development
