Repository neutrinojs/neutrino, pull requests merged in 2019-11, with the labels that each got.

#1478 Fix wrong function name in documentation example
  docs/middleware.md
Labels: docs

#1477 Allow passed extensions to override defaults
  packages/neutrino/Neutrino.js
  packages/neutrino/test/api_test.js
Labels: bug

#1481 Drop support for Node.js 8
  .travis.yml
  docs/contributing/development.md
  docs/installation/index.md
  docs/migration-guide.md
  package.json
  packages/airbnb-base/README.md
  packages/airbnb-base/package.json
  packages/airbnb/README.md
  packages/airbnb/package.json
  packages/banner/README.md
  packages/banner/package.json
  packages/clean/README.md
  packages/clean/package.json
  packages/compile-loader/README.md
  packages/compile-loader/package.json
  packages/copy/README.md
  packages/copy/package.json
  packages/create-project/package.json
  packages/dev-server/README.md
  packages/dev-server/package.json
  packages/eslint/README.md
  packages/eslint/package.json
  packages/font-loader/README.md
  packages/font-loader/package.json
  packages/html-loader/README.md
  packages/html-loader/package.json
  packages/html-template/README.md
  packages/html-template/package.json
  packages/image-loader/README.md
  packages/image-loader/package.json
  packages/jest/README.md
  packages/jest/package.json
  packages/karma/README.md
  packages/karma/package.json
  packages/library/README.md
  packages/library/package.json
  packages/migrate/package.json
  packages/mocha/README.md
  packages/mocha/package.json
  packages/neutrino/package.json
  packages/node/README.md
  packages/node/package.json
  packages/preact/README.md
  packages/preact/package.json
  packages/react-components/README.md
  packages/react-components/package.json
  packages/react/README.md
  packages/react/package.json
  packages/standardjs/README.md
  packages/standardjs/package.json
  packages/start-server/README.md
  packages/start-server/package.json
  packages/style-loader/README.md
  packages/style-loader/package.json
  packages/style-minify/README.md
  packages/style-minify/package.json
  packages/vue/README.md
  packages/vue/package.json
  packages/web/README.md
  packages/web/package.json
Labels: breaking change

#1482 Correct the repository definition in package.json
  packages/airbnb-base/package.json
  packages/airbnb/package.json
  packages/banner/package.json
  packages/clean/package.json
  packages/compile-loader/package.json
  packages/copy/package.json
  packages/create-project/package.json
  packages/dev-server/package.json
  packages/eslint/package.json
  packages/font-loader/package.json
  packages/html-loader/package.json
  packages/html-template/package.json
  packages/image-loader/package.json
  packages/jest/package.json
  packages/karma/package.json
  packages/library/package.json
  packages/migrate/package.json
  packages/mocha/package.json
  packages/neutrino/package.json
  packages/node/package.json
  packages/preact/package.json
  packages/react-components/package.json
  packages/react/package.json
  packages/standardjs/package.json
  packages/start-server/package.json
  packages/style-loader/package.json
  packages/style-minify/package.json
  packages/web/package.json
Labels: bug

#1484 Change useBuiltIns to usage
  docs/migration-guide.md
  packages/library/README.md
  packages/library/index.js
  packages/node/README.md
  packages/node/index.js
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/react/index.js
  packages/vue/README.md
  packages/web/README.md
  packages/web/index.js
Labels: breaking change

#1487 Docs: Add v8 to v9 migration instructions for WebWorkers
  docs/migration-guide.md
Labels: docs

#1488 react: Use babel-preset-react's new useSpread option
  packages/react/index.js
Labels: feature
