Repository neutrinojs/neutrino, pull requests merged in 2019-04, with the labels that each got.

#1341 Set core-js version in preset-env if used
  packages/library/index.js
  packages/library/package.json
  packages/node/index.js
  packages/node/package.json
  packages/preact/README.md
  packages/react/README.md
  packages/vue/README.md
  packages/web/README.md
  packages/web/index.js
  packages/web/package.json
Labels: bug

#1349 [v8.x] Docs: create-new-project grammar fix
  docs/installation/create-new-project.md
Labels: docs

#1355 Fix generation of changelog during release:prepare
  docs/contributing/development.md
  package.json
Labels: development

#1356 Refresh lockfile & bump in-range dependency versions
  package.json
  packages/airbnb-base/package.json
  packages/airbnb/package.json
  packages/compile-loader/package.json
  packages/copy/package.json
  packages/jest/package.json
  packages/library/package.json
  packages/migrate/package.json
  packages/mocha/package.json
  packages/neutrino/package.json
  packages/node/package.json
  packages/preact/package.json
  packages/react/package.json
  packages/standardjs/package.json
  packages/vue/package.json
  packages/web/package.json
  yarn.lock
Labels: cleanup

#1359 Further tweaks to the release process
  docs/contributing/development.md
  package.json
  yarn.lock
Labels: development

#1358 v9.0.0-rc.1
  CHANGELOG.md
  lerna.json
  packages/airbnb-base/package.json
  packages/airbnb/package.json
  packages/banner/package.json
  packages/clean/package.json
  packages/compile-loader/package.json
  packages/copy/package.json
  packages/create-project/package.json
  packages/dev-server/package.json
  packages/eslint/package.json
  packages/font-loader/package.json
  packages/html-loader/package.json
  packages/html-template/package.json
  packages/image-loader/package.json
  packages/jest/package.json
  packages/karma/package.json
  packages/library/package.json
  packages/migrate/package.json
  packages/mocha/package.json
  packages/neutrino/package.json
  packages/node/package.json
  packages/preact/package.json
  packages/react-components/package.json
  packages/react/package.json
  packages/standardjs/package.json
  packages/start-server/package.json
  packages/style-loader/package.json
  packages/style-minify/package.json
  packages/vue/package.json
  packages/web/package.json
Labels: breaking change, development

#1365 Fix using create-project with a single project selection
  packages/create-project/commands/init/index.js
  packages/create-project/test/cli_test.js
Labels: bug

#1366 Only use useBuiltIns when coupled with core-js
  packages/library/index.js
  packages/node/index.js
  packages/web/index.js
Labels: bug

#1371 Switching to running Node.js 12 in travis
  .travis.yml
Labels: development
