Repository neutrinojs/neutrino, pull requests merged in 2019-03, with the labels that each got.

#1314 Omit cacheDirectory from jest middleware babel options
  packages/jest/package.json
  packages/jest/src/index.js
Labels: bug

#1316 Fix inspect test output from interfering with ava logging
  packages/neutrino/test/package_test.js
Labels: development

#1317 Remove package.json config in favor of config files for husky and lint-staged
  .huskyrc.js
  lint-staged.config.js
  package.json
Labels: development

#1315 Remove extra externals usage in library middleware
  packages/library/index.js
Labels: bug

#1319 Disable use of externals in library preset during testing
  packages/library/index.js
Labels: bug

#1321 Add test for library externals
  packages/library/test/library_test.js
Labels: development

#1320 Upgrade dependencies
  yarn.lock
Labels: dependency

#1324 Bump in-range dependency versions
  package.json
  packages/airbnb-base/package.json
  packages/airbnb/package.json
  packages/clean/package.json
  packages/compile-loader/package.json
  packages/copy/package.json
  packages/create-project/package.json
  packages/eslint/package.json
  packages/font-loader/package.json
  packages/image-loader/package.json
  packages/jest/package.json
  packages/karma/package.json
  packages/library/package.json
  packages/mocha/package.json
  packages/neutrino/package.json
  packages/node/package.json
  packages/preact/package.json
  packages/react/package.json
  packages/standardjs/package.json
  packages/style-loader/package.json
  packages/vue/package.json
  packages/web/package.json
  yarn.lock
Labels: feature

#1325 Update to Lerna v3 and switch to a 2-stage release process
  docs/contributing/development.md
  lerna.json
  package.json
  scripts/test-create-project-ci.sh
  yarn.lock
Labels: development

#1330 Remove unmaintained pwa middleware
  docs/customization.md
  docs/migration-guide.md
  docs/packages/pwa.md
  mkdocs.yml
  packages/pwa/.npmignore
  packages/pwa/README.md
  packages/pwa/index.js
  packages/pwa/package.json
  packages/pwa/pwa.js
  packages/pwa/test/middleware_test.js
Labels: breaking change

#1334 jest: Exclude mjs from moduleFileExtensions
  packages/jest/src/index.js
  packages/jest/test/jest_test.js
Labels: bug

#1335 react: Enable eslint-plugin-react-hooks rules
  packages/react/index.js
Labels: breaking change, feature

#1338 Improve migration documentation and add more legacy option checks
  docs/migration-guide.md
  packages/neutrino/Neutrino.js
  packages/neutrino/test/api_test.js
Labels: bug, docs

#1339 docs: Move the quickstart section above manual installation
  packages/airbnb-base/README.md
  packages/airbnb/README.md
  packages/jest/README.md
  packages/karma/README.md
  packages/library/README.md
  packages/mocha/README.md
  packages/node/README.md
  packages/preact/README.md
  packages/react-components/README.md
  packages/react/README.md
  packages/standardjs/README.md
  packages/vue/README.md
  packages/web/README.md
Labels: docs

#1305 Adding Zoho Sites Template development preset to docs.
  docs/learning-resources.md
Labels: docs

#1322 Remove targets from library preset to force es2015 target
  packages/library/README.md
  packages/library/index.js
  packages/library/test/library_test.js
Labels: bug

#1340 Create project refactor and use react hooks implementation
  package.json
  packages/create-project/commands/init/constants.js
  packages/create-project/commands/init/index.js
  packages/create-project/commands/init/matrix.js
  packages/create-project/commands/init/questions.js
  packages/create-project/commands/init/templates/neutrino/.neutrinorc.js.ejs
  packages/create-project/commands/init/templates/react-components/src/components/Example/index.jsx
  packages/create-project/commands/init/templates/react-components/src/components/HelloWorld/index.jsx
  packages/create-project/commands/init/templates/react-components/src/index.jsx
  packages/create-project/commands/init/templates/react/src/App.jsx
  packages/create-project/commands/init/utils.js
  packages/create-project/test/cli_test.js
Labels: cleanup, feature
