Repository neutrinojs/neutrino, pull requests merged in 2020-06, with the labels that each got.

#1579 Travis: Switch from Xenial to Focal build image
  .travis.yml
Labels: development

#1582 Release v9.2.0
  CHANGELOG.md
  lerna.json
  packages/airbnb-base/package.json
  packages/airbnb/package.json
  packages/banner/package.json
  packages/clean/package.json
  packages/compile-loader/package.json
  packages/copy/package.json
  packages/create-project/package.json
  packages/dev-server/package.json
  packages/eslint/package.json
  packages/font-loader/package.json
  packages/html-loader/package.json
  packages/html-template/package.json
  packages/image-loader/package.json
  packages/jest/package.json
  packages/karma/package.json
  packages/library/package.json
  packages/migrate/package.json
  packages/mocha/package.json
  packages/neutrino/package.json
  packages/node/package.json
  packages/preact/package.json
  packages/react-components/package.json
  packages/react/package.json
  packages/standardjs/package.json
  packages/start-server/package.json
  packages/style-loader/package.json
  packages/style-minify/package.json
  packages/vue/package.json
  packages/web/package.json
Labels: development

#1580 Enable @babel/preset-env's ShippedProposals mode
  packages/library/index.js
  packages/node/index.js
  packages/preact/index.js
  packages/preact/package.json
  packages/react/index.js
  packages/react/package.json
  packages/web/index.js
Labels: feature

#1577 jest: Fix configuration of Webpack aliases
  packages/jest/src/index.js
  packages/jest/test/jest_test.js
Labels: bug

#1590 neutrino: Fix check for legacy array middleware
  packages/neutrino/Neutrino.js
Labels: bug

#1588 jest: Support using the preset standalone
  packages/jest/src/index.js
  packages/jest/test/jest_test.js
Labels: feature
