Repository neutrinojs/neutrino, pull requests merged in 2020-10, with the labels that each got.

#1629 Make tests not fail on Windows due to EOL
  packages/migrate/test/migrate_test.js
Labels: development

#1592 Docs: Improve wording of the FAQ
  docs/faq.md
Labels: docs

#1612 Add neutrino --inspect support for alternative config filenames
  docs/usage.md
  packages/neutrino/bin/neutrino.js
Labels: feature
